self=`basename $0`

cat << EOF
#
# DO NOT EDIT THIS FILE
#
# It is automatically generated by $self using templates
# from ${SOURCEPATH}/isolinux/config
#
EOF

for i in ${SOURCEPATH}/isolinux/config/* ; do
  case "$i" in
	# emacsen backup files. FIXME: support other editors
	*~) ;;
	# emacsen autosave files. FIXME: support other editors
	\#*\#) ;;
	*)
    echo
    echo "### BEGIN $i ###"
    "$i"
    echo "### END $i ###"
	;;
  esac
done
