#!/bin/sh

# Bail out if booting a System Rescue CD image

#check for SRCD release file or similar
 
grep -q 'initrd=initram.igz BOOT_IMAGE=' /proc/cmdline && exit

[[ -n "$BROWSER" ]] && $BROWSER index.html || firefox index.html || mozilla-firefox index.html || mozilla index.html || chromium index.html || google-chrome index.html || konqueror index.html || opera index.html

