#!/bin/sh

[[ -n "$BROWSER" ]] && $BROWSER index.html || xdg-open index.html || chromium index.html || google-chrome index.html || firefox index.html || mozilla-firefox index.html || mozilla index.html  || konqueror index.html || opera index.html

